### ISSUE TITLE
Assimp crashes in RelWithDebInfo

### ISSUE THREAD

**Issue by Cooble** [Cooble/NiceDay#17]
During FBX scene import:
this line at FBXMaterial.cpp:89 
`std::transform(shading.begin(), shading.end(), shading.begin(), Assimp::ToLower<char>);`
causes crash due to `shading.begin()`

But in Release and in Debug it works properly.

**Comment by MomoDeve** [comment]
created a pull request with fixes: https://github.com/assimp/assimp/pull/3471. As a temporary workaround, you can replace that line with this:
`std::transform(shading.data(), shading.data() + shading.size(), std::addressof(shading[0]), Assimp::ToLower<char>);`

**Comment by MomoDeve** [comment]
My changes were merged into assimp's master branch. Check if this issue is resolved

**Comment by Cooble** [comment]
Awesome, it works flawlessly. Thanks.
