### ISSUE TITLE
Cannot run samples due to missing files

### ISSUE THREAD

**Issue by MomoDeve** [Cooble/NiceDay#19]
Engine tries to unconditionally load files from the `res/models` folder, which is not in the repository as it is added to `.gitignore`. As a result, engine cannot find the folder and crashes. Maybe just add these files to repo or at least provide a way to download them?

https://github.com/Cooble/NiceDay/search?q=res/models

**Comment by Cooble** [comment]
Okie Dokie so:
Added `DownloadAdditionalResources.bat` that will download needed resources from specific github release.
Also did a minor overhaul of res folder structure which was in fact atrocious. :/

For now the whole clone and run proccess should as simple as:
1. `git clone --recurse-submodules  (--depth=1) https://github.com/Cooble/NiceDay.git`
2. In parallel can be:
   - `External-WIN32-Build.bat` 
   - `DownloadAdditionalResources.bat` 
   - `InstallMono.bat`
3. `start NiceDaySolution.sln` or `cmake --build . --config Release --target SandboxTest`
